### ISSUE TITLE
Stall when extracting using ocr on macos from pdf with embedded images

### ISSUE THREAD

**Issue by nmammeri** [yobix-ai/extractous#23]
- Process stalls until killed, when running on MacOS with OCR enabled with PDF documents that  has embedded images in them.
- OCR works fine with direct images but the bug is seen only on PDFs with embedded images
- Tests failing (stalling forever) eng-ocr.pdf and deu-ocr.pdf 

Initial investigation points to the [bad handling of AWT within GraalVM ](https://github.com/oracle/graal/issues/4921). I think it's due to the AWT dispose thread deadlocking.

**Comment by xueyou2000** [comment]
same issues

**Comment by cpursley** [comment]
I'd love a solution to this. I'm not even sure what to troubleshoot or log.

**Comment by guchengxi1994** [comment]
I have the same issue, but I cannot extract content even to string

```rust
#[test]
    fn test_read_file() {
        // Get the command-line arguments
        let file_path =
            "path-to-my-pdf.pdf";

        // Extract the provided file content to a string
        let extractor = Extractor::new()
            .set_pdf_config(PdfParserConfig::new().set_ocr_strategy(PdfOcrStrategy::NO_OCR));
        // if you need an xml
        // extractor = extractor.set_xml_output(true);

        let (content, metadata) = extractor.extract_file_to_string(file_path).unwrap();
        println!("{}", content);
        println!("{:?}", metadata);
    }
```


```
java.lang.UnsatisfiedLinkError: Can't load library: awt | java.library.path = [.Djava.awt.headless=trueFailed creating the graal native vm,  Failed creating the graal native from pointer,  NO_OCROCR_AND_TEXT_EXTRACTIONAUTO]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryRelative(NativeLibraries.java:141)
        at java.base@23.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:108)
        at java.base@23.0.2/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base@23.0.2/java.lang.System.loadLibrary(System.java:2066)
        at java.desktop@23.0.2/java.awt.image.ColorModel$1.run(ColorModel.java:211)
        at java.desktop@23.0.2/java.awt.image.ColorModel$1.run(ColorModel.java:209)
        at java.base@23.0.2/java.security.AccessController.executePrivileged(AccessController.java:132)
        at java.base@23.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop@23.0.2/java.awt.image.ColorModel.loadLibraries(ColorModel.java:208)
        at java.desktop@23.0.2/java.awt.image.ColorModel.<clinit>(ColorModel.java:221)
        at java.desktop@23.0.2/java.awt.image.Raster.<clinit>(Raster.java:172)
        at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:107)
        at org.apache.tika.parser.pdf.PDFParser.getPDDocument(PDFParser.java:506)
        at org.apache.tika.parser.pdf.PDFParser.getPDDocument(PDFParser.java:474)
        at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:191)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
        at ai.yobix.TikaNativeMain.parseToStringWithConfig(TikaNativeMain.java:192)
        at ai.yobix.TikaNativeMain.parseFileToString(TikaNativeMain.java:87)
test test::tests::test_read_file ... FAILED
```

**Comment by snewcomer** [comment]
Same issue on linux

```
Exception in thread "main": java.lang.UnsatisfiedLinkError
java.lang.UnsatisfiedLinkError: Can't load library: awt | java.library.path = [.Djava.awt.headless=truefrom_raw ptr argumentFailed creating the graal native vm,  Failed creating the graal native from pointer,  ]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryRelative(NativeLibraries.java:141)
	at java.base@23.0.1/java.lang.ClassLoader.loadLibrary(ClassLoader.java:108)
	at java.base@23.0.1/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base@23.0.1/java.lang.System.loadLibrary(System.java:2066)
	at java.desktop@23.0.1/java.awt.image.ColorModel$1.run(ColorModel.java:211)
	at java.desktop@23.0.1/java.awt.image.ColorModel$1.run(ColorModel.java:209)
	at java.base@23.0.1/java.security.AccessController.executePrivileged(AccessController.java:132)
	at java.base@23.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop@23.0.1/java.awt.image.ColorModel.loadLibraries(ColorModel.java:208)
	at java.desktop@23.0.1/java.awt.image.ColorModel.<clinit>(ColorModel.java:221)
	at java.desktop@23.0.1/java.awt.image.Raster.<clinit>(Raster.java:172)
	at org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:107)
	at org.apache.tika.parser.pdf.PDFParser.getPDDocument(PDFParser.java:506)
	at org.apache.tika.parser.pdf.PDFParser.getPDDocument(PDFParser.java:474)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:191)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
	at ai.yobix.TikaNativeMain.parseToStringWithConfig(TikaNativeMain.java:192)
	at ai.yobix.TikaNativeMain.parseFileToString(TikaNativeMain.java:87)
```

```
    match extractor.extract_file_to_string(&path) {
        Ok((content, metadata)) => Ok((content, format!("{:?}", metadata))),
        Err(e) => Err(rustler::Error::Term(Box::new(format!("Extraction failed: {}", e))))
    }
}
```

**Comment by snewcomer** [comment]
Is it possible the source machine still needs a Java runtime environment to resolve this?

**Comment by franc** [comment]
same on linux

**Comment by Syazvinski** [comment]
+1

**Comment by opeolluwa** [comment]
+1

**Comment by opeolluwa** [comment]
@nmammeri @snewcomer did you find any fix for it
